### ISSUE TITLE
Database locked?

### ISSUE THREAD

**Issue by pacarevolution** [doZennn/steam-categories#2]
Hello! I'm getting the following error everytime I try to run the example code provided in the readme.md:

Key not found in database [_https://steamloopback.host U*my-user-id*-cloud-storage-namespaces]

The path of the database and the user id i provided are fine and Steam is closed while running the script.
Any clues?
Thanks!

**Comment by doZennn** [comment]
Is the second parameter your proper user id? It needs to be in the Steam3 format.

**Comment by pacarevolution** [comment]
Hello! Thanks for the quick reply! Yes, I checked that. My steam ID3 is this one: U:1:61129513

**Comment by pacarevolution** [comment]
I tried running this code in the "db" parameter after it's created:

`this.db.createReadStream()
                    .on('data', function (data) {
                        console.log(data.key, '=', data.value)
                    })
                    .on('error', function (err) {
                        console.log('Oh my!', err)
                    })
                    .on('close', function () {
                        console.log('Stream closed')
                    })
                    .on('end', function () {
                        console.log('Stream ended')
                    });`

And it just logs "Stream ended" and "Stream closed". Does it mean the database is empty?

**Comment by pacarevolution** [comment]
I'm running the code in a simple html application via Chrome. Maybe that's the problem?

**Comment by doZennn** [comment]
Does Chrome have access to the database you're pointing it to?

**Comment by pacarevolution** [comment]
Mmm... maybe that's the problem! I don't know how to do that.

**Comment by doZennn** [comment]
You can probably use this in a browser with some modifications...  
But unless you really need to use this library in a browser, you're better off using it with Node. I haven't tested using it with a browser and probably won't since I don't really see the use for this in one.

**Comment by pacarevolution** [comment]
Okay! I'll give it a try with Node!

**Comment by pacarevolution** [comment]
It works perfectly through Node. Thanks for the help!!
